Repository wagtail/docker-wagtail-develop, pull requests merged in 2020-10, with the labels that each got.

#17 Add command for updating repos
  update.sh
Labels: enhancement

#16 Drop unnecessary user from web container
  docker-compose.linux.yml
Labels: bug

#18 Reworked the database and Wagtail installation setup
  .dockerignore
  .gitignore
  Dockerfile
  README.md
  docker-compose.yml
  setup-db.sh
Labels: hacktoberfest-accepted
